version: 2
defaults: &defaults
  docker:
    - image: circleci/python:3.7.3

jobs:
  test:
    working_directory: ~/app
    <<: *defaults
    steps:
      - checkout:
          path: ~/app
      - attach_workspace:
          at: ~/app
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7.3/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.dev.txt
      - save_cache:
          key: dev-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7.3/site-packages"
      - restore_cache:
          key: dev-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            cd test
            pipenv run pytest -s

  deploy:
    working_directory: ~/app
    <<: *defaults
    steps:
      - checkout:
          path: ~/app
      - attach_workspace:
          at: ~/app
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run: sudo npm install -g serverless
      - run: npm install
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - ~/.cache/npm
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7.3/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.txt
      - save_cache:
          key: deploy-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7.3/site-packages"
      - restore_cache:
          key: deploy-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}-{{ arch }}
      - run: sls deploy --stage dev

workflows:
  version: 2
  deploy-workflows:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
